# Generated by Django 3.1.2 on 2020-10-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('archived', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
