# Generated by Django 3.1.2 on 2020-10-24 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201024_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnote',
            name='note_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.notegroup'),
        ),
    ]
