# Generated by Django 3.1.2 on 2020-10-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201024_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('archived', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now=True)),
                ('content', models.TextField()),
                ('note_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.notegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ListNoteEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_text', models.TextField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('parent_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.listnote')),
            ],
        ),
    ]
