# Generated by Django 3.1.2 on 2020-10-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_listnote_listnoteentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='notegroup',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
