# Generated by Django 3.1.2 on 2020-10-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_notegroup_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listnote',
            name='content',
        ),
    ]
