# Generated by Django 3.1.2 on 2020-10-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_listnote_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
